USE FIRMA;

SELECT ADRESSE FROM ANGESTELLTER;

SELECT ADRESSE FROM ANGESTELLTER WHERE NNAME='SMITH';

SELECT ADRESSE, GDATUM FROM ANGESTELLTER WHERE GESCHLECHT = 'M';

SELECT ADRESSE, GDATUM FROM ANGESTELLTER WHERE GESCHLECHT = 'M' AND ABT = 5;