USE FIRMA;

#Folie 55
SELECT ADRESSE FROM ANGESTELLTER;

SELECT ADRESSE FROM ANGESTELLTER WHERE NNAME='SMITH';

SELECT ADRESSE, GDATUM FROM ANGESTELLTER WHERE GESCHLECHT = 'M';

SELECT ADRESSE, GDATUM FROM ANGESTELLTER WHERE GESCHLECHT = 'M' AND ABT = 5;

#Folie 57
SELECT ANGESTELLTER.NNAME, ANGESTELLTER.VNAME, ANGESTELLTER.ADRESSE, ANGESTELLTER.ABT
    FROM ANGESTELLTER, ABTEILUNG
    WHERE ABTEILUNG.ANAME = 'Research' AND ABT = ABTNUMMER;
SELECT NNAME, ADRESSE FROM ANGESTELLTER INNER JOIN ABTEILUNG ON ABT = ABTNUMMER
    WHERE ANAME = 'Research';

#Folie 60
SELECT PROJEKT.PNAME, ABTEILUNG.ANAME, ANGESTELLTER.NNAME, ANGESTELLTER.ADRESSE
    FROM PROJEKT, ABTEILUNG, ANGESTELLTER
    WHERE PROJEKT.PSTANDORT = 'Stafford'
       #AND ABTEILUNG.ABTNUMMER = PROJEKT.ABTNR
        AND PROJEKT.ABTNR = ANGESTELLTER.ABT
        AND ABTEILUNG.MGRSSN = ANGESTELLTER.SSN;

#Folie 64
SELECT ANGESTELLTER.VNAME AS ANGESTELLTER_VORNAME,
       ANGESTELLTER.NNAME AS ANGESTELLTER_NACHNAME,
       ANGESTELLTER.ADRESSE AS ANGESTELLTER_ADRESSE
    FROM ANGESTELLTER, ABTEILUNG
    WHERE ABTEILUNG.ANAME = 'Research'
        AND ABTEILUNG.ABTNUMMER = ANGESTELLTER.ABT;

#Folie 70
SELECT GEHALT FROM ANGESTELLTER;

SELECT DISTINCT GEHALT FROM ANGESTELLTER;

#Folie 73
SELECT PNUMMER FROM PROJEKT, ARBEITET_AN, ANGESTELLTER
    WHERE NNAME='Wong' AND SSN = ESSN AND PNR = PNUMMER
UNION
SELECT PNUMMER FROM PROJEKT, ANGESTELLTER, ABTEILUNG
    WHERE NNAME = 'Wong' AND MGRSSN = SSN AND ABTNUMMER = ABTNR;

#Folie 75
SELECT ANGESTELLTER.NNAME, ANGESTELLTER.ADRESSE
    FROM ANGESTELLTER
    WHERE ADRESSE LIKE '%Houston%';
SELECT ANGESTELLTER.NNAME, ANGESTELLTER.ADRESSE
    FROM ANGESTELLTER
    WHERE ADRESSE LIKE '%Houston____';                  #equivalent _ entspricht irgeneinem zeichen

#Folie 77
SELECT ANGESTELLTER.NNAME, ANGESTELLTER.GEHALT*1.1 AS GEHALT_NEU
    FROM ANGESTELLTER, ARBEITET_AN, PROJEKT
    WHERE PROJEKT.PNAME = 'ProductX'
        AND PROJEKT.PNUMMER = ARBEITET_AN.PNR
        AND ARBEITET_AN.ESSN = ANGESTELLTER.SSN;

#Folie 79
    #PNAME AUFSTEIGEND
SELECT ANGESTELLTER.NNAME, PROJEKT.PNAME
    FROM ANGESTELLTER, ARBEITET_AN, PROJEKT
    WHERE ANGESTELLTER.SSN = ARBEITET_AN.ESSN
        AND ARBEITET_AN.PNR = PROJEKT.PNUMMER
    ORDER BY PNAME ASC;

    #NNAME ABSTEIGEND
SELECT ANGESTELLTER.NNAME, PROJEKT.PNAME
    FROM ANGESTELLTER, ARBEITET_AN, PROJEKT
    WHERE ANGESTELLTER.SSN = ARBEITET_AN.ESSN
        AND ARBEITET_AN.PNR = PROJEKT.PNUMMER
    ORDER BY NNAME DESC;

#Folie 84
SELECT ANGESTELLTER.NNAME, ANGESTELLTER.VNAME, ANGESTELLTER.GEHALT
    FROM ANGESTELLTER
    WHERE GEHALT > ALL (
        SELECT ANGESTELLTER.GEHALT
        FROM ANGESTELLTER
        WHERE ANGESTELLTER.ABT = 5
        );

#Folie 88
SELECT A.VNAME, A.NNAME
    FROM ANGESTELLTER AS A
    WHERE SSN IN
        (SELECT ESSN FROM ANGEHOERIGER
            WHERE A.GESCHLECHT = GESCHLECHT);

#ohne Schachtelung
SELECT ANGESTELLTER.VNAME, ANGESTELLTER.NNAME
    FROM ANGESTELLTER, ANGEHOERIGER
    WHERE SSN = ESSN
        AND ANGEHOERIGER.GESCHLECHT = ANGESTELLTER.GESCHLECHT;