DROP TABLE IF EXISTS ABT_STANDORT;

CREATE TABLE IF NOT EXISTS ABT_STANDORT
(
    ABTNUMMER           INT,
    ASTANDORT           VARCHAR(255),

    PRIMARY KEY (ABTNUMMER, ASTANDORT)
);

# ABTEILUNG_STANDORT
INSERT INTO ABT_STANDORT VALUES (1, 'Houston');
INSERT INTO ABT_STANDORT VALUES (4, 'Stafford');
INSERT INTO ABT_STANDORT VALUES (5, 'Bellaire');
INSERT INTO ABT_STANDORT VALUES (5, 'Sugarland');
INSERT INTO ABT_STANDORT VALUES (5, 'Houston');