USE FIRMA;

# ANGESTELLTER

ALTER TABLE ANGESTELLTER
    ADD CONSTRAINT ANGESTELLTER__SUPERSSNN_ANGESTELLTER_SSN
        FOREIGN KEY (SUPERSSN) REFERENCES ANGESTELLTER(SSN)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE ANGESTELLTER DROP CONSTRAINT ANGESTELLTER__SUPERSSNN_ANGESTELLTER_SSN;


ALTER TABLE ANGESTELLTER
    ADD CONSTRAINT ABT__ABTEILUNG_ABTNUMMER
        FOREIGN KEY (ABT) REFERENCES ABTEILUNG(ABTNUMMER)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE ANGESTELLTER DROP CONSTRAINT ABT__ABTEILUNG_ABTNUMMER;


# ABTEILUNG

ALTER TABLE ABTEILUNG
    ADD CONSTRAINT MGRSSN__ANGESTELLTER_SSN
        FOREIGN KEY (MGRSSN) REFERENCES ANGESTELLTER(SSN)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE ABTEILUNG DROP CONSTRAINT MGRSSN__ANGESTELLTER_SSN;


# ABT_STANDORT

ALTER TABLE ABT_STANDORT
    ADD CONSTRAINT ABTNUMMER__ABTEILUNG_ABNUMMER
        FOREIGN KEY (ABTNUMMER) REFERENCES ABTEILUNG(ABTNUMMER)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

ALTER TABLE ABT_STANDORT DROP CONSTRAINT ABTNUMMER__ABTEILUNG_ABNUMMER;


# PROJEKT

ALTER TABLE PROJEKT
    ADD CONSTRAINT ABTNR__ABTEILUNG_ABTNUMMER
        FOREIGN KEY (ABTNR) REFERENCES ABTEILUNG(ABTNUMMER)
            ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE PROJEKT DROP CONSTRAINT ABTNR__ABTEILUNG_ABTNUMMER;


#ARBEITE_AN

ALTER TABLE ARBEITET_AN
    ADD CONSTRAINT ESSN__ANESTELLTER_SSN
        FOREIGN KEY (ESSN) REFERENCES ANGESTELLTER(SSN)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

ALTER TABLE ARBEITET_AN DROP CONSTRAINT ESSN__ANESTELLTER_SSN;


ALTER TABLE ARBEITET_AN
    ADD CONSTRAINT PNR__PROJEKT_PNUMMER
        FOREIGN KEY (PNR) REFERENCES PROJEKT(PNUMMER)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

ALTER TABLE ARBEITET_AN DROP CONSTRAINT PNR__PROJEKT_PNUMMER;


#ANGEHOERIGER

ALTER TABLE ANGEHOERIGER
    ADD CONSTRAINT ESSN__ANGESTELLTER_SSN2
        FOREIGN KEY (ESSN) REFERENCES ANGESTELLTER(SSN)
            ON DELETE RESTRICT
            ON UPDATE CASCADE;

ALTER TABLE ANGEHOERIGER DROP CONSTRAINT ESSN__ANGESTELLTER_SSN2;