CREATE SCHEMA TESTDATENBANK;

USE TESTDATENBANK;

CREATE TABLE IF NOT EXISTS Angestellter(

    NNAME       VARCHAR(15)     NOT NULL,
    GDATUM      DATE,
    GEHALT      DECIMAL(10,2),
    SSN         CHAR(9),
    SUPERSSN    CHAR(9),
    ABT         INT             DEFAULT 1,

    PRIMARY KEY (SSN),          #KEINE CONSTRAINT BENAMSUNG

    CONSTRAINT ANGESTSUPERFK    #OPTIONAL
        FOREIGN KEY(SUPERSSN) REFERENCES Angestellter(SSN)
                ON DELETE SET NULL
                ON UPDATE CASCADE
);

SHOW SCHEMAS;
SHOW TABLES;
SHOW COLUMNS FROM Angestellter;

DROP SCHEMA TESTDATENBANK;